db:
  image: sameersbn/postgresql:9.1-1
  environment:
    - DB_USER=docs
    - DB_PASS=secretpassword
    - DB_NAME=docs
  volumes:
    - ./pgsql:/var/lib/postgresql
readthedocs:
  build: .
  environment:
    RTD_HAS_REDIS: 'true'
    PGPASSWORD: secretpassword
  ports:
    - "80:8000"
  links:
    - db
    - elasticsearch
    - redis
  volumes:
    - ./user_builds:/app/user_builds
    - ./ssh:/root/.ssh
elasticsearch:
  image: jfroche/elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - ./es:/var/lib/elasticsearch
redis:
  image: redis
